package com.spazomatic.nabsta.db;

import com.spazomatic.nabsta.db.dao.DaoSession;
import de.greenrobot.dao.DaoException;

import com.spazomatic.nabsta.db.dao.ArtistDao;
import com.spazomatic.nabsta.db.dao.ImageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ARTIST.
 */
public class Artist {

    private Long id;
    private String name;
    private Long image_id_fk;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient ArtistDao myDao;

    private Image image;
    private Long image__resolvedKey;


    public Artist() {
    }

    public Artist(Long id) {
        this.id = id;
    }

    public Artist(Long id, String name, Long image_id_fk) {
        this.id = id;
        this.name = name;
        this.image_id_fk = image_id_fk;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getArtistDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getImage_id_fk() {
        return image_id_fk;
    }

    public void setImage_id_fk(Long image_id_fk) {
        this.image_id_fk = image_id_fk;
    }

    /** To-one relationship, resolved on first access. */
    public Image getImage() {
        Long __key = this.image_id_fk;
        if (image__resolvedKey == null || !image__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ImageDao targetDao = daoSession.getImageDao();
            Image imageNew = targetDao.load(__key);
            synchronized (this) {
                image = imageNew;
            	image__resolvedKey = __key;
            }
        }
        return image;
    }

    public void setImage(Image image) {
        synchronized (this) {
            this.image = image;
            image_id_fk = image == null ? null : image.getId();
            image__resolvedKey = image_id_fk;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
